name: Deploy Website to EC2

on:
  push:
    branches:
      - main # Or 'master', depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy with rsync
        run: |
          # Use the ssh-agent to connect and rsync to transfer files
          # -avz: archive, verbose, compress
          # --delete: deletes extra files in TARGET_DIR that are not in source
          # --exclude '.git/': don't copy the git folder itself
          # --exclude 'node_modules/': if you have node_modules, don't copy
          # --exclude '.env': don't copy sensitive .env files if present
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}
