name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "=== DIAGNOSTIC INFORMATION ==="
            echo "Current working directory: $(pwd)"
            echo "Web server status:"
            sudo systemctl status nginx --no-pager || echo "Nginx not running"
            sudo systemctl status apache2 --no-pager || echo "Apache2 not running"
            echo "Web root contents before deployment:"
            ls -la /var/www/html/ || echo "Cannot access /var/www/html/"
            echo "Nginx configuration:"
            sudo nginx -T 2>/dev/null | grep "root" || echo "Cannot get nginx config"
            echo "=== STARTING DEPLOYMENT ==="
            cd /tmp
            rm -rf portfolio
            git clone https://github.com/temurxon-abulqosimov/portfolio.git
            cd portfolio
            echo "Repository contents:"
            ls -la
            echo "=== COPYING FILES ==="
            sudo rm -rf /var/www/html/*
            sudo cp -r * /var/www/html/
            sudo cp -r .* /var/www/html/ 2>/dev/null || true
            echo "Web root contents after deployment:"
            ls -la /var/www/html/
            echo "=== SETTING PERMISSIONS ==="
            sudo chown -R www-data:www-data /var/www/html/
            sudo chmod -R 755 /var/www/html/
            echo "=== RESTARTING SERVICES ==="
            sudo systemctl restart nginx
            sudo systemctl restart apache2 2>/dev/null || true
            echo "=== FINAL STATUS ==="
            sudo systemctl status nginx --no-pager
            echo "Deployment completed at: $(date)"
           
